version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: training

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1
